### ISSUE TITLE
LSTM model not available?

### ISSUE THREAD

**Issue by giosal** [akb89/ortografix#4]
When trying to launch the training with LSTM model I get the following error message:
```
Traceback (most recent call last):
  File "/home/giosal/.pyenv/versions/3.7.7/bin/ortografix", line 10, in <module>
    sys.exit(main())
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ortografix/main.py", line 452, in main
    args.func(args)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ortografix/main.py", line 223, in train
    args.output_dirpath)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ortografix/main.py", line 155, in _train
    teacher_forcing_ratio)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ortografix/main.py", line 95, in _train_single_batch
    encoder_hidden)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ortografix/model/encoder.py", line 59, in forward    return self.lstm(embedded_tensor, hidden_tensor)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 556, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 512, in check_forward_args
    'Expected hidden[0] size {}, got {}')
  File "/home/giosal/.pyenv/versions/3.7.7/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 176, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, tuple(hx.size())))
RuntimeError: Expected hidden[0] size (1, 1, 256), got (1, 256)
```
I see that it still goes in RNN package of pyTorch. maybe I misunderstan how to specify LSTM model?

**Comment by akb89** [comment]
Fixed with v0.3.5
